name: "terraform"
on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: checkout
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform init
        id: rm
        run: rm ./inventory


      - name: terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color

      - name: apply
        id: apply
        run: terraform apply --auto-approve


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          pip install ansible
          ansible --version

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yaml
          directory: ./
          key: ${{secrets.PRIVATE_KEY_PATH}}
